/**
 * Full clinic patient notification set — first four showcase info / success / warning / error.
 */
import type { NotificationItem } from './types';

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'appt-pending',
    category: 'health',
    title: 'Appointment Pending',
    body: 'Your request with Dr. Danica Joie B. Antonio was submitted. Please wait for Health Service confirmation.',
    timeLabel: '1 min ago',
    read: false,
    href: '/(tabs)/appointments',
    source: 'Health Service',
    notificationType: 'info',
  },
  {
    id: 'appt-confirmed',
    category: 'health',
    title: "You're All Set",
    body: 'Your appointment is confirmed. Arrive a few minutes early and bring your school ID.',
    timeLabel: 'Yesterday',
    read: true,
    href: '/(tabs)/appointments',
    source: 'Health Service',
    notificationType: 'success',
  },
  {
    id: 'appt-reminder',
    category: 'health',
    title: 'Visit In 30 Minutes',
    body: 'Your clinic appointment starts soon. Please head to the Health Service Office.',
    timeLabel: 'Last Month',
    read: true,
    href: '/(tabs)/appointments',
    source: 'Health Service',
    notificationType: 'warning',
  },
  {
    id: 'appt-cancelled',
    category: 'health',
    title: 'Appointment Cancelled',
    body: 'Your scheduled clinic visit was cancelled. Book a new slot with a campus doctor anytime.',
    timeLabel: 'Last Month',
    read: true,
    href: '/(tabs)/appointments',
    source: 'Health Service',
    notificationType: 'error',
  },
  {
    id: 'queue-turn',
    category: 'health',
    title: "It's Your Turn",
    body: 'Please proceed to the physician station and present your queue ticket.',
    timeLabel: '2h ago',
    read: false,
    href: '/(tabs)/appointments',
    source: 'Health Service',
    notificationType: 'info',
  },
  {
    id: 'visit-completed',
    category: 'health',
    title: 'Visit Completed',
    body: 'Your consultation is done. Review this visit under Medical Records.',
    timeLabel: '3 days ago',
    read: true,
    href: '/(tabs)/history',
    source: 'Health Service',
    notificationType: 'success',
  },
  {
    id: 'reschedule',
    category: 'health',
    title: 'Please Pick A New Time',
    body: 'Your provider is unavailable for the original slot. Choose another available schedule.',
    timeLabel: '5 days ago',
    read: false,
    href: '/(tabs)/appointments',
    source: 'Health Service',
    notificationType: 'warning',
  },
  {
    id: 'clinic-break',
    category: 'campus',
    title: 'Clinic On Break',
    body: 'The Health Service Office is on break and will reopen later today. Later bookings stay available.',
    timeLabel: '6 days ago',
    read: true,
    href: '/(tabs)/appointments',
    source: 'Health Service',
    notificationType: 'info',
  },
  {
    id: 'medcert-ready',
    category: 'health',
    title: 'Medical Certificate Ready',
    body: 'Your medical certificate is ready. Open Medical Records or claim it at the Health Service Office.',
    timeLabel: '1 week ago',
    read: true,
    href: '/(tabs)/history',
    source: 'Health Service',
    notificationType: 'success',
  },
  {
    id: 'missed-visit',
    category: 'health',
    title: 'We Missed You',
    body: "You didn't check in for your scheduled visit. Book again if you still need care.",
    timeLabel: '2 weeks ago',
    read: true,
    href: '/(tabs)/appointments',
    source: 'Health Service',
    notificationType: 'warning',
  },
  {
    id: 'clinic-advisory',
    category: 'campus',
    title: 'Clinic Advisory',
    body: 'If you have fever or cough, wear a mask when visiting and tell the nurse at triage.',
    timeLabel: '3 weeks ago',
    read: true,
    href: '/(tabs)',
    source: 'Health Service',
    notificationType: 'info',
  },
];
